### ISSUE TITLE
NK_GK11 error

### ISSUE THREAD

**Issue by Alexle1709** [IMFS-MMB/mmb-gui-electron#80] opened 2019-12-02 11:31 UTC
Hi,
I cannot run model NK_GK11 with any policy rule. I run it alone and combine with other model, both did not work. The error is in the picture. I use matlab and window. Thanks.
![Screenshot (16)](https://user-images.githubusercontent.com/45760141/69956176-99eec700-14ff-11ea-96d9-1f3c710f86c4.png)

**Comment by gboehl** [comment] 2019-12-02 17:43
Strange. But seems to be an issue with the model. @AlexDece @JTWendelborn, could one of you have a look?

**Comment by JTWendelborn** [comment] 2019-12-02 21:13
I had a quick look at it and the issue is that the steady state file in the folder was called NK_GK11_orig_steadystate.m instead of only NK_GK11_steadystate.m. Therefore, the mod-file did not find the steady state and no solution. It works fine when we just rename the file. However, I also had a look at the steady state file in the old MMB 2.3.2, which is slightly different (and also works for the model). Here is a screenshot of the differences (lhs: steady state file from new mmb, res: steady state file from old mmb):
![Problem_GK11](https://user-images.githubusercontent.com/34969113/69995491-7011c080-1550-11ea-9f3d-7dd6ebe9f573.png)

@gboehl  Which of these files should be included? If you let me know, I can make the changes and send a PR.

**Comment by gboehl** [comment] 2019-12-02 21:25
Thanks Jonas! Alex was removing some of the old files in #75, though I can't find the steady state files in this PR (and I thought I checked when I merged it). In any case, he kept the backups (and any old file can of course be found in the commit history).

Maybe you can track down when the files got lost, because potentially more harm was done in the same commit. 

It seems that the lhs steady state file contains adaptation to be able to run with octave, so thats probably the one.

**Comment by AlexDece** [comment] 2019-12-02 21:38
I didnt delete a steadystate file in #75. I thought the name was on purpose
and left it there.

**Comment by JTWendelborn** [comment] 2019-12-02 21:40
Alright, then renaming should be fine! I'll do it right away and send the PR!

**Comment by gboehl** [comment] 2019-12-02 21:56
Thanks! 

@AlexDece I know. Just wanted to provide clues.

Solved by #84

**Closed by gboehl** 2019-12-02 21:56 UTC
