### ISSUE TITLE
No output if models provide different numbers of timeseries/variables

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#101] opened 2019-12-06 21:08 UTC
**Describe the bug**
No output at all if NK_LWW03 & NK_MCN99cr & NK_MI14 are compared with all possible policy rules, although Dynare runs through. 

**To Reproduce**
1. Select NK_LWW03 & NK_MCN99cr & NK_MI14, all possible rules together (all except OW08; user rule: i(-1)=0.8, infl=1.5, outputgap=0.5, outputgap(-1)=0.25 ), monetary policy shock

**Desktop :**
 - OS: WIN10
 - Matlab2019a
 - Dynare 4.5.7

**Comment by gboehl** [comment] 2019-12-06 21:20
True that. Each model taken alone runs and results are plotted.

The thing is: NK_MI14 displays 4 variables, NK_MCN99cr or NK_LWW03 don't show output (although it is set to true in the `capabilities` section in the JSON).

@btatar13 can you check whats wrong with output?
@j2L4e plotting should work even though some models do not provide time series for all variables

**Comment by btatar13** [comment] 2019-12-06 21:30
> True that. Each model taken alone runs and results are plotted.
> The thing is: NK_MI14 displays 4 variables, NK_MCN99cr or NK_LWW03 don't show output (although it is set to true in the capabilities section in the JSON).
> @btatar13 can you check whats wrong with output?
> @j2L4e plotting should work even though some models do not provide time series for all variables

Actually, there is no Output in LWW03 nor in MCN99cr. I guess that adjusting the JSON files will solve the issue.

**Comment by gboehl** [comment] 2019-12-06 21:50
Can not confirm. LWW03 & MCN99 work, each taken separately and both together under Linux/Octave.

**Comment by btatar13** [comment] 2019-12-06 23:01
OK, the Problem is the following:

1. LWW03 JSON file has to be corrected as no Output
**2. Although Output is set to false, the Output variable is still available, which is a bug in the software! MI14 has Output in the model, but the other two models do not have it! As the number of the variables is different, no charts are shown. The same happens if you run any model with no output defined, e.g. CGG99 together with a model where Output is defined, e.g. MI14. If you uncheck output, everything runs**


To cut a long story short, Output should be made unavailable, if a model is compared in which there is no Output variable defined.

**Comment by j2L4e** [comment] 2019-12-07 00:39
> Although Output is set to false, the Output variable is still available, which is a bug in the software

Works as intended. Super common shocks/vars are always shown.

The actual bug was fixed in b52c09901c69fe566dc713796fd2617bf5473e25 and 52686d2a5aca04bc0ba1c1bc1a97ab5c8969e419

**Closed by j2L4e** 2019-12-07 00:39 UTC

**Comment by btatar13** [comment] 2019-12-07 01:05
This just leads to the above problem, that is, some models can not be compared and for the user it is not going to be clear why.
