### ISSUE TITLE
NK_AFL15 does not work under (Mac+Linux)/Matlab2019b

### ISSUE THREAD

**Issue by JTWendelborn** [IMFS-MMB/mmb-gui-electron#112] opened 2019-12-09 15:30 UTC
**Describe the bug**
The model NK_AFL15 gives an error under Mac/Matlab 2019b. The issue does not occur under Mac/Matlab 2019a or Mac/Octave 5.1, we also tried Windows/Matlab 2019b where it also worked, so this seems to be a specific Mac/Matlab2019b issue...so I don't know how important it is.

**To Reproduce**
1. Select NK_AFL15
2. Select e.g. Taylor 1993 rule and Monetary Policy Shock
3. Compare

**Screenshots**
![Error_AFL15](https://user-images.githubusercontent.com/34969113/70447921-dc844680-1a9f-11ea-9bf3-9098fd43ee6f.png)

**Additional context**
Again, this problem only occurred under Matlab 2019b and for both Mac-users. Also, it occurs in both, the build and the dev version.

I will try to find out what's behind it, but I'm not very optimistic to be successful.

**Comment by j2L4e** [comment] 2019-12-09 15:37
Confirmed on linux/matlab

unsubbing as it doesn't seem GUI related

**Comment by gboehl** [comment] 2019-12-09 17:21
Seems to be a dynare bug. Lets keep it for later...

**Comment by JTWendelborn** [comment] 2019-12-12 09:40
I found the solution: to use the `fsolve` command you need the Optimization Toolbox, which I had installed for Matlab 2019a, but not for 2019b...after installing, the model runs.

**Comment by JTWendelborn** [comment] 2019-12-12 09:41
I will add a footnote in the model list and note in the json-description.

**Comment by gboehl** [comment] 2019-12-12 16:05
Great. Close this issue when you are done. Thanks!

**Closed** 2019-12-12 18:35 UTC
Labels: wontfix
