### ISSUE TITLE
Compatibility test runs through, but error message

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#89] opened 2019-12-04 17:26 UTC
**Describe the bug**
Compatibility test runs through, but an error message is displayed that output could not be captured and therefore simulations can produce wron results
[MMB_error_test.pptx](https://github.com/IMFS-MMB/mmb-gui-electron/files/3923165/MMB_error_test.pptx)

**To Reproduce**
Hit 'Check compatibility'

**Screenshots**
Attached

**Desktop:**
 - OS: Windows 10
 - Dynare 4.5.7
 - Matlab 2019a

**Additional context**
The error occurs also using the 2019b version

**Comment by j2L4e** [comment] 2019-12-04 17:30
Thanks, closing as it's a dupe of #87

**Closed by j2L4e** 2019-12-04 17:30 UTC
