### ISSUE TITLE
'Plot variances' activated then no graphs/output 

### ISSUE THREAD

**Issue by btatar13** [IMFS-MMB/mmb-gui-electron#91] opened 2019-12-04 17:56 UTC
**Describe the bug**
If under Options plot variances is activated there is no graphs/output at all.

**To Reproduce**
Check 'plot variances' under options

**Desktop :**
 - Windows 10
 - Dynare 4.5.7
 - Matlab 2019a

**Comment by j2L4e** [comment] 2019-12-04 19:49
I think that's been fixed already. Please download the latest version once when the current build is done:

https://ci.appveyor.com/project/mmb-ci/mmb-gui-electron/builds/29317882

**Comment by j2L4e** [comment] 2019-12-04 19:55
I'll close this as I can't reproduce the issue on the current version, please reopen if it still appears.

**Closed by j2L4e** 2019-12-04 19:55 UTC
Labels: GUI
